version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:10.1'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=root
      # - MARIADB_DATABASE=shop
      - MARIADB_PASSWORD=
    ports: 
      - 3306:3306

  myapp:
    tty: true
    image: bitnami/laravel:6
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=root
      - DB_DATABASE=shop
      - DB_PASSWORD=
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    # privileged: true # Privileged mode could be required to run this container under Windows
